### ISSUE TITLE
Where do the SMI files come from?

### ISSUE THREAD

**Issue by cthoyt** [PatWalters/yamc#14]
I'm curious where the SMI files in https://github.com/PatWalters/yamc/tree/main/data come from. Did someone generate these a long time ago with targeted queries on ChEMBL, and now the data gets passed around? Or is it something you created?

**Comment by cthoyt** [comment]
After a bit more playing around, I think I've figured out how to re-generate your databses, given the ChEMBL ID for the target. See https://nbviewer.org/github/cthoyt/chembl-downloader/blob/a68bef1c12a8bb53f78687ee8af4971de32c01ba/notebooks/refresh-static-data.ipynb :)

**Comment by PatWalters** [comment]
See the README.  Datafiles are from https://pubs.acs.org/doi/10.1021/acs.jcim.8b00542

**Comment by PatWalters** [comment]
Nice workflow, I definitely will borrow that one.
